In [ ]:
import numpy as np

class Simplex:
    def __init__(self, resource_availability, decision_variables, objective_function, resource_constraints):
        self.resource_availability = resource_availability
        self.decision_variables = decision_variables
        self.objective_function = objective_function
        self.resource_constraints = resource_constraints
        self.num_decision_vars = len(decision_variables)
        self.num_constraints = len(resource_constraints)

        # Create initial tableau
        self.create_tableau()

    def create_tableau(self):
        # Create a matrix with zeros
        self.tableau = np.zeros((self.num_constraints + 1, self.num_decision_vars + self.num_constraints + 1))

        # Fill the tableau with coefficients
        self.tableau[0, :self.num_decision_vars] = self.objective_function
        self.tableau[1:, :self.num_decision_vars] = self.resource_constraints

        # Identity matrix for slack variables
        self.tableau[1:, self.num_decision_vars:self.num_decision_vars+self.num_constraints] = np.eye(self.num_constraints)

        # Last column for resource availability
        self.tableau[1:, -1] = self.resource_availability

    def pivot_column(self):
        pivot_col = np.argmin(self.tableau[0, :-1])
        return pivot_col

    def pivot_row(self, pivot_col):
        ratios = self.tableau[1:, -1] / self.tableau[1:, pivot_col]
        pivot_row = np.argmin(ratios) + 1
        return pivot_row

    def apply_pivot(self, pivot_row, pivot_col):
        pivot_element = self.tableau[pivot_row, pivot_col]

        # Divide pivot row by pivot element to make pivot element 1
        self.tableau[pivot_row, :] /= pivot_element

        # Perform row operations to make other elements in pivot column 0
        for i in range(len(self.tableau)):
            if i != pivot_row:
                factor = self.tableau[i, pivot_col]
                self.tableau[i, :] -= factor * self.tableau[pivot_row, :]

    def is_optimal(self):
        return all(self.tableau[0, :-1] >= 0)

    def solve(self):
        # Print the initial tableau
        print("\nInitial Tableau:")
        print(self.tableau)

        iteration = 1
        while not self.is_optimal():
            print(f"\nIteration {iteration}:")
            pivot_col = self.pivot_column()
            pivot_row = self.pivot_row(pivot_col)
            print("Pivot column:", pivot_col)
            print("Pivot row:", pivot_row)
            print("Pivot element:", self.tableau[pivot_row, pivot_col])
            self.apply_pivot(pivot_row, pivot_col)
            print("\nTableau after pivoting:")
            print(self.tableau)
            iteration += 1

        print("\nOptimal Solution:")
        for i, var in enumerate(self.decision_variables):
            col = np.where(self.tableau[:, i] == 1)[0]
            if len(col) == 0:
                print(f"{var} = 0")
            else:
                print(f"{var} = {self.tableau[col[0], -1]}")

        print("Optimal Value of Objective Function:", -self.tableau[0, -1])  # Multiply by -1 to get the actual objective value

# Define problem parameters
resource_availability = [2400, 2000, 2200]
decision_variables = ['X', 'Y']
objective_function = [-24, -15]  # Coefficients are negated compared to the previous version
resource_constraints = [[0, 0.5],
                        [1, 0],
                        [0, 1]]

# Instantiate and solve the simplex problem
simplex = Simplex(resource_availability, decision_variables, objective_function, resource_constraints)
simplex.solve()



Initial Tableau:
[[-2.4e+01 -1.5e+01  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  5.0e-01  1.0e+00  0.0e+00  0.0e+00  2.4e+03]
 [ 1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  2.0e+03]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  1.0e+00  2.2e+03]]

Iteration 1:
Pivot column: 0
Pivot row: 2
Pivot element: 1.0

Tableau after pivoting:
[[ 0.0e+00 -1.5e+01  0.0e+00  2.4e+01  0.0e+00  4.8e+04]
 [ 0.0e+00  5.0e-01  1.0e+00  0.0e+00  0.0e+00  2.4e+03]
 [ 1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  2.0e+03]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  1.0e+00  2.2e+03]]

Iteration 2:
Pivot column: 1
Pivot row: 3
Pivot element: 1.0

Tableau after pivoting:
[[ 0.0e+00  0.0e+00  0.0e+00  2.4e+01  1.5e+01  8.1e+04]
 [ 0.0e+00  0.0e+00  1.0e+00  0.0e+00 -5.0e-01  1.3e+03]
 [ 1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  2.0e+03]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  1.0e+00  2.2e+03]]

Optimal Solution:
X = 2000.0
Y = 2200.0
Optimal Value of Objective Function: -81000.0


<ipython-input-1-92bb7bd782df>:34: RuntimeWarning: divide by zero encountered in divide
  ratios = self.tableau[1:, -1] / self.tableau[1:, pivot_col]
